### ISSUE TITLE
Home Assistant / Hassio integration

### ISSUE THREAD

**Issue by Newman820** [T3m3z/pyvesteltv#3]
How can I integrate this to Home Assistant? I have a Vestel TV (branded Luxor) that I wan´t to control some basic functions on from HA. First and most basic is that I want to turn TV off.

**Comment by T3m3z** [comment]
Hello!

I actually wrote this to be general library to allow controlling of Procaster LE-50F449 so I cannot guarantee that it works with your TV. Different Vestel TV sets seem to have different ways of controlling them so I cannot guarantee that this will work with your TV set.

I realized that I hadn't uploaded custom component that uses this library to integrate HA to my TV set. I created a repository for the custom component that I have written to fulfill my needs: https://github.com/T3m3z/HA-Vestel-Component

I hope that this helps with what you are trying to achieve :) Please note that you might face some difficulties as you try this and I might not be able to help with all of them as our TV sets might function in a completely different way.

Another possibility to control On/Off -state of your TV could be using IR transmitter. If you are into electronics, I can warmly recommend [ESPHome Remote Transmitter](https://esphome.io/components/remote_transmitter.html). I have also used Raspberry Pi + Kodi media center + CEC to control the on/off state of my TV set but this does not allow full control.

**Comment by terrafirma2021** [comment]
Hi mate thank you for making this, any chance you can help with steps to install,

Cheers

**Comment by T3m3z** [comment]
Hi @terrafirma2021 !

This pyvesteltv library is just a library. You can (in most cases) install it using command ```pip install --upgrade pyvesteltv```. But please note that this library does not do anything on its own. If you are interested in Home Assistant component, please check [HA-Vestel-Component](https://github.com/T3m3z/HA-Vestel-Component). You can find installation instructions from Readme.md of that repository. But please note that this component has been tested only using 1 TV model so it might not work 100% for yours.

Br,
Teemu
